from pathlib import Path
import re

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from tech_doc_agent.app.api.frontend import (
    FRONTEND_UNAVAILABLE_DETAIL,
    install_frontend,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def test_legacy_frontend_bundle_is_removed_from_current_entrypoint():
    frontend_dir = PROJECT_ROOT / "frontend"

    assert not (frontend_dir / "app.js").exists()
    assert "/src/main.tsx" in (frontend_dir / "index.html").read_text(encoding="utf-8")


def test_repository_frontend_build_is_served_when_dist_exists():
    dist_dir = PROJECT_ROOT / "frontend" / "dist"
    if not (dist_dir / "index.html").is_file():
        pytest.skip("frontend/dist is generated by the frontend build job")

    app = FastAPI()
    install_frontend(app, dist_dir=dist_dir)
    client = TestClient(app)

    index = client.get("/")
    assert index.status_code == 200
    asset_match = re.search(r'(?:src|href)="(/assets/[^"]+)"', index.text)
    assert asset_match is not None

    asset = client.get(asset_match.group(1))
    assert asset.status_code == 200
    assert asset.content


@pytest.mark.parametrize("route", ["/", "/studio", "/inspector", "/learner"])
def test_frontend_routes_return_explicit_503_when_dist_is_missing(
    tmp_path: Path,
    route: str,
):
    app = FastAPI()
    install_frontend(app, dist_dir=tmp_path / "missing-dist")

    response = TestClient(app).get(route)

    assert response.status_code == 503
    assert response.json() == {"detail": FRONTEND_UNAVAILABLE_DETAIL}
    assert "/src/main.tsx" not in response.text


def test_built_frontend_index_and_hashed_asset_are_served(tmp_path: Path):
    dist_dir = tmp_path / "dist"
    assets_dir = dist_dir / "assets"
    assets_dir.mkdir(parents=True)
    (dist_dir / "index.html").write_text(
        '<!doctype html><div id="root"></div><script type="module" '
        'src="/assets/index-test.js"></script>',
        encoding="utf-8",
    )
    (assets_dir / "index-test.js").write_text(
        'document.querySelector("#root").textContent = "ready";',
        encoding="utf-8",
    )
    app = FastAPI()
    install_frontend(app, dist_dir=dist_dir)
    client = TestClient(app)

    for route in ("/", "/studio", "/inspector", "/learner"):
        response = client.get(route)
        assert response.status_code == 200
        assert '/assets/index-test.js' in response.text

    asset = client.get("/assets/index-test.js")
    assert asset.status_code == 200
    assert 'textContent = "ready"' in asset.text
    assert "javascript" in asset.headers["content-type"]


def test_source_frontend_directory_is_not_mounted_as_static(tmp_path: Path):
    dist_dir = tmp_path / "dist"
    dist_dir.mkdir()
    (dist_dir / "index.html").write_text("<!doctype html><div>dist</div>", encoding="utf-8")
    app = FastAPI()
    install_frontend(app, dist_dir=dist_dir)

    response = TestClient(app).get("/static/src/main.tsx")

    assert response.status_code == 404


def test_container_build_generates_dist_and_compose_does_not_mask_it():
    dockerfile = (PROJECT_ROOT / "Dockerfile").read_text(encoding="utf-8")
    compose = (PROJECT_ROOT / "docker-compose.yml").read_text(encoding="utf-8")

    assert "FROM node:22-alpine AS frontend-builder" in dockerfile
    assert "RUN npm ci" in dockerfile
    assert "RUN npm run build" in dockerfile
    assert "COPY --from=frontend-builder /frontend/dist /app/frontend/dist" in dockerfile
    assert "./frontend:/app/frontend" not in compose
