from __future__ import annotations

UNCATEGORIZED = "uncategorized"

_CATEGORY_PREFIXES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("langgraph_advanced", ("langgraph 进阶", "langgraph checksaver", "langgraph memorysaver", "langgraph redissaver", "langgraph postgressaver")),
    ("langgraph_core", ("langgraph 核心", "langgraph stategraph")),
    ("agent_arch", ("agent 架构", "router agent", "planner agent", "worker agent", "supervisor pattern", "handoff pattern", "react agent", "plan-and-execute", "tool-calling agent", "multi-agent collaboration")),
    ("tool_calling", ("tool calling", "openai function calling")),
    ("rag_advanced", ("rag 进阶",)),
    ("rag_basic", ("rag 基础", "rag（", "rag ", "rag chunk", "rag metadata")),
    ("vector_db", ("向量数据库", "faiss", "qdrant", "milvus", "pgvector", "chroma")),
    ("langchain", ("langchain", "langsmith")),
    ("fastapi", ("fastapi",)),
    ("backend", ("后端工程", "pydantic-settings")),
    ("observability", ("可观测性", "opentelemetry", "langfuse tracing")),
    ("eval", ("评测体系",)),
    ("data_cache", ("数据与缓存", "redis persistence", "redis ", "alembic migration")),
    ("api_design", ("api 与系统设计", "http status code", "jwt", "oauth", "rbac")),
    ("llm_engineering", ("llm 应用工程", "prompt injection")),
)

_CATEGORY_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "langgraph_advanced",
        (
            "langgraph 进阶",
            "memorysaver",
            "redissaver",
            "postgressaver",
            "checkpoint namespace",
            "checkpoint_ns",
            "time travel",
            "human-in-the-loop",
            "interrupt_before",
            "interrupt_after",
            "parallel branches",
            "fan-out",
            "fan-in",
            "recursion limit",
            "langgraph studio",
            "multi agent handoff",
            "多 agent handoff",
        ),
    ),
    (
        "langgraph_core",
        (
            "langgraph 核心",
            "langgraph stategraph",
            "graph 概念",
            "stategraph",
            "typeddict state",
            "pydantic state",
            "reducer",
            "add_messages",
            "pregel",
            "subgraph",
            "conditional edge",
            "checkpoint 机制",
            "interrupt 机制",
        ),
    ),
    (
        "agent_arch",
        (
            "agent 架构",
            "router agent",
            "planner agent",
            "worker agent",
            "supervisor pattern",
            "handoff pattern",
            "tool-calling agent",
            "react agent",
            "plan-and-execute",
            "reflection",
            "self-critique",
            "multi-agent collaboration",
            "agent state design",
            "agent memory",
            "agent retry",
            "fallback 机制",
        ),
    ),
    (
        "tool_calling",
        (
            "tool calling",
            "function calling",
            "tool schema",
            "tool_choice",
            "parallel tool calls",
            "tool call id",
            "tool result message",
            "structured output",
            "json mode",
            "pydantic tool schema",
            "sensitive tools",
            "tool approval",
            "tool timeout",
            "tool error handling",
            "tool observability",
        ),
    ),
    (
        "rag_advanced",
        (
            "rag 进阶",
            "recall@k",
            "mrr",
            "ndcg",
            "negative retrieval",
            "semantic drift",
            "lost in the middle",
            "multi-query",
            "hyde",
            "parent-child",
            "late chunking",
            "semantic chunking",
            "context window management",
            "retrieval evaluation dataset",
        ),
    ),
    (
        "rag_basic",
        (
            "rag 基础",
            "chunking",
            "chunk size",
            "chunk overlap",
            "embedding",
            "vector search",
            "bm25",
            "hybrid search",
            "rrf",
            "reranker",
            "query rewrite",
            "metadata filter",
            "document loader",
            "retrieval pipeline",
            "context compression",
            "citation",
            "grounding",
            "检索增强生成",
        ),
    ),
    (
        "vector_db",
        (
            "向量数据库",
            "faiss",
            "qdrant",
            "milvus",
            "pgvector",
            "chroma",
            "vector distance",
            "cosine similarity",
            "l2 distance",
            "inner product",
            "ann index",
            "hnsw",
            "ivf",
            "product quantization",
        ),
    ),
    (
        "langchain",
        (
            "langchain",
            "chatmodel",
            "runnable",
            "prompttemplate",
            "chatprompttemplate",
            "messagesplaceholder",
            "outputparser",
            "lcel",
            "langsmith",
        ),
    ),
    (
        "fastapi",
        (
            "fastapi",
            "apirouter",
            "depends",
            "dependency injection",
            "yield dependency",
            "lifespan",
            "middleware",
            "exception handler",
            "streamingresponse",
            "sse",
            "cors",
            "backgroundtasks",
            "testclient",
            "async route",
        ),
    ),
    (
        "backend",
        (
            "后端工程",
            "settings management",
            "pydantic-settings",
            "environment variables",
            "docker compose",
            "health check",
            "readiness probe",
            "structured logging",
            "trace_id",
            "request_id",
            "graceful shutdown",
            "resource container",
            "lazy initialization",
        ),
    ),
    (
        "observability",
        (
            "可观测性",
            "langfuse",
            "opentelemetry",
            "structured logs",
            "span",
            "trace",
            "callback handler",
            "token usage",
            "latency p50",
            "latency p95",
            "error rate",
            "tool timing",
            "node timing",
            "sse event timing",
            "eval report",
            "dashboard",
        ),
    ),
    (
        "eval",
        (
            "评测体系",
            "agent eval",
            "single-turn eval",
            "multi-turn eval",
            "plan match",
            "keyword score",
            "latency score",
            "tool call count",
            "interrupted status",
            "baseline",
            "regression test",
            "golden dataset",
            "judge function",
            "offline eval",
            "online eval",
        ),
    ),
    (
        "data_cache",
        (
            "数据与缓存",
            "redis",
            "rdb",
            "aof",
            "redis stream",
            "redis pub/sub",
            "cache aside",
            "ttl",
            "lru",
            "session store",
            "sqlite",
            "postgresql",
            "sqlmodel",
            "sqlalchemy",
            "alembic",
        ),
    ),
    (
        "api_design",
        (
            "api 与系统设计",
            "restful api",
            "http status code",
            "idempotency",
            "pagination",
            "rate limiting",
            "authentication",
            "jwt",
            "oauth",
            "rbac",
            "openapi",
            "webhook",
            "retry policy",
            "circuit breaker",
        ),
    ),
    (
        "llm_engineering",
        (
            "llm 应用工程",
            "prompt injection",
            "jailbreak",
            "pii redaction",
            "guardrails",
            "model routing",
            "fallback model",
            "cost control",
            "token budget",
            "streaming output",
            "empty response retry",
            "llm timeout",
            "llm rate limit",
            "response validation",
        ),
    ),
)

_VALID_CATEGORIES = {category for category, _ in _CATEGORY_RULES}

_CATEGORY_ALIASES = {
    "langgraph核心": "langgraph_core",
    "langgraph_core": "langgraph_core",
    "langgraph进阶": "langgraph_advanced",
    "langgraph_advanced": "langgraph_advanced",
    "agent架构": "agent_arch",
    "agent_arch": "agent_arch",
    "toolcalling": "tool_calling",
    "tool_calling": "tool_calling",
    "functioncalling": "tool_calling",
    "rag基础": "rag_basic",
    "rag_basic": "rag_basic",
    "ragbasic": "rag_basic",
    "rag进阶": "rag_advanced",
    "rag_advanced": "rag_advanced",
    "ragadvanced": "rag_advanced",
    "向量数据库": "vector_db",
    "vectordb": "vector_db",
    "vector_db": "vector_db",
    "后端工程": "backend",
    "可观测性": "observability",
    "评测体系": "eval",
    "数据与缓存": "data_cache",
    "data_cache": "data_cache",
    "api与系统设计": "api_design",
    "api_design": "api_design",
    "llm应用工程": "llm_engineering",
    "llm_engineering": "llm_engineering",
}

_BROAD_CATEGORY_TAGS = {
    "rag": ["rag"],
    "rag相关": ["rag"],
    "rag有关": ["rag"],
    "langgraph": ["langgraph"],
    "langgraph相关": ["langgraph"],
    "langgraph有关": ["langgraph"],
}

def tagify(value: str) -> str:
    return value.strip().casefold().replace(" ", "_").replace("（", "_").replace("）", "").replace("(", "_").replace(")", "")


def category_alias_key(value: str) -> str:
    return (
        value.casefold()
        .replace(" ", "")
        .replace("_", "")
        .replace("-", "")
        .replace("（", "")
        .replace("）", "")
        .replace("(", "")
        .replace(")", "")
        .replace("相关的内容", "相关")
        .replace("相关内容", "相关")
        .replace("有关的内容", "有关")
        .replace("有关内容", "有关")
    )


CATEGORY_PREFIXES = _CATEGORY_PREFIXES
CATEGORY_RULES = _CATEGORY_RULES
VALID_CATEGORIES = _VALID_CATEGORIES
CATEGORY_ALIASES = _CATEGORY_ALIASES
BROAD_CATEGORY_TAGS = _BROAD_CATEGORY_TAGS

__all__ = [
    "BROAD_CATEGORY_TAGS",
    "CATEGORY_ALIASES",
    "CATEGORY_PREFIXES",
    "CATEGORY_RULES",
    "UNCATEGORIZED",
    "VALID_CATEGORIES",
    "category_alias_key",
    "tagify",
]
